🔀::인게임 카드 정보 UI
Team-QSS/KonoPuro-Unity pull request #22
Opened 2024-06-04 11:13 UTC by whitefish2n2

- 인게임 내 카드 정보 UI 구현

2024-06-04 11:19 UTC, hsung3407 submitted a review, later dismissed

2024-06-04 11:23 UTC, Mooner510 commented on Assets/FirstCard.cs
> +            if (Physics.Raycast(ray, out hit, Mathf.Infinity, 1 << 6)) {
`Infinity`로 끝까지 추적하는 것 보다는 적당한 거리도 나쁘지 않을 것 같아요

2024-06-04 11:29 UTC, Mooner510 commented on Assets/Gachabox/Draw.cs
> +
`Update()`는 안 사용한다면 지워둡시다! 선언만으로 성능에 영향 줄 수 있어요

2024-06-04 11:29 UTC, Mooner510 commented on Assets/_root/Script/Title/TitleManager.cs
> +		Invoke("LogSuccess",2f);
Invoke를 사용한 이유가 있을까요?

2024-06-04 11:29 UTC, Mooner510 commented on Assets/cardinrange/CardinrandomRange.cs
> +
사용 안 한다면 지우는게 좋을 것 같아요

2024-06-04 11:29 UTC, Mooner510 commented on Assets/cardinrange/ExitGatcha.cs
> +
위와 동일

2024-06-04 11:29 UTC, Mooner510 commented on Assets/cardinrange/SpriteArray.cs
> +
위와 동일

2024-06-04 14:11 UTC, oty0365 commented on Assets/_root/Script/Title/TitleManager.cs
> +		Invoke("LogSuccess",2f);
Invoke를 사용한 이유는 로그인 성공 오브젝트를 2초간 띄우고 다시 비 활성화하게 하기 위해서 넣었습니다.
사실 Coroutine이나 다른 방법을 사용했어도 되었습니다..

2024-06-05 05:02 UTC, Mooner510 commented on Assets/_root/Script/Title/TitleManager.cs
> +		Invoke("LogSuccess",2f);
@oty0365 
Invoke를 다른 걸로 바꾸라는 뜻이 아니라 저기에 시간 주어 실행한 이유가 궁금했었습니다!
Invoke를 이용해 함수 이름을 제공하여 입력하는 것 보다 nameof 키워드를 이용하여 리팩토링시의 오류를 줄일 수 있습니다!

2024-06-05 09:06 UTC, hsung3407 approved these changes

2024-06-05 09:23 UTC, Mooner510 requested changes

2024-06-05 09:23 UTC, Mooner510 commented on Assets/FirstCard.cs
> +            if (Physics.Raycast(ray, out hit, 15f, 1 << 6)) {
현재 해당 Raycast가 회원가입 혹은 로그인 UI가 표시되어도 작동합니다.
다음과 같은 방법으로 해결할 수 있을 것 같습니다.
- UI가 표시 되었을 때 카드 콜라이더들을 가리는 큰 오브젝트 생성하고 레이어 적용시켜 블로킹
- UI가 표시 되었을 때 해당 기능이 잠시 중단되도록 if문 추가 (가장 좋을 듯 함)
- UI가 표시 되었을 때 UI도 해당 레이어에 추가하여 UI가 레이에 맞았을 경우 블로킹

2024-06-06 06:24 UTC, oty0365 commented on Assets/FirstCard.cs
> +            if (Physics.Raycast(ray, out hit, 15f, 1 << 6)) {
2번째 방법으로 고쳐보겠습니다

2024-06-09 04:24 UTC, Mooner510 commented
혹시 설마 같은 수정 내역을 서로 다른 PR로 개시하신건가요..?
@oty0365 @whitefish2n2

2024-06-10 10:40 UTC, whitefish2n2 commented
으아아아아악 오찬영

2024-06-11 06:46 UTC, Mooner510 submitted a review, later dismissed
이후 및 요청한 수정 요청은 개발이 지연될 수 있기에 직접 수정하겠습니다

2024-06-11 06:47 UTC, hsung3407 approved these changes

2024-06-11 06:47 UTC, Mooner510 submitted a review, later dismissed

2024-06-11 06:50 UTC, hsung3407 approved these changes

2024-06-11 06:50 UTC, merged