login
Team-QSS/KonoPuro-Unity pull request #6
Opened 2024-05-02 14:19 UTC by kkm1010k

add login sequence

2024-05-02 14:40 UTC, hsung3407 commented
회원가입 기능도 추가해주세요

2024-06-04 10:41 UTC, hsung3407 requested changes
이거 바꿔라

2024-06-04 10:43 UTC, hsung3407 requested changes
바꿔라

2024-06-04 10:43 UTC, hsung3407 commented on Assets/_root/Script/Manager/TimelineManager.cs
> +        isChanging = false;
정확히 이거 바꾸셈

2024-06-15 13:27 UTC, Mooner510 commented
@kkm1010k 추가 내용 없으시면 6월 20일에 닫겠습니다

2024-06-20 01:49 UTC, closed without merging